class Patient { final String id, name, email, medicalId; final DateTime dateOfBirth; const Patient({required this.id,required this.name,required this.email,required this.medicalId,required this.dateOfBirth}); Map<String,dynamic> toJson()=>{'id':id,'name':name,'email':email,'medicalId':medicalId,'dateOfBirth':dateOfBirth.toIso8601String()}; factory Patient.fromJson(Map<String,dynamic> j)=>Patient(id:j['id'],name:j['name'],email:j['email'],medicalId:j['medicalId'],dateOfBirth:DateTime.parse(j['dateOfBirth'])); }
class Doctor { final String id,name,specialty,hospital; const Doctor({required this.id,required this.name,required this.specialty,required this.hospital}); Map<String,dynamic> toJson()=>{'id':id,'name':name,'specialty':specialty,'hospital':hospital}; factory Doctor.fromJson(Map<String,dynamic> j)=>Doctor(id:j['id'],name:j['name'],specialty:j['specialty'],hospital:j['hospital']); }
class Appointment {final String id;final Doctor doctor;final DateTime scheduledAt;final String status;const Appointment({required this.id,required this.doctor,required this.scheduledAt,required this.status});Map<String,dynamic>toJson()=>{'id':id,'doctor':doctor.toJson(),'scheduledAt':scheduledAt.toIso8601String(),'status':status};factory Appointment.fromJson(Map<String,dynamic>j)=>Appointment(id:j['id'],doctor:Doctor.fromJson(j['doctor']),scheduledAt:DateTime.parse(j['scheduledAt']),status:j['status']);}
class Medicine {final String id,name,dosage,purpose,schedule,doctor,howToTake,foodInstructions,sideEffects,notes;final int remaining,initialQuantity,dailyUsage;final bool taken;const Medicine({required this.id,required this.name,required this.dosage,required this.purpose,required this.schedule,required this.remaining,this.doctor='Dr. Ananya Rao',this.howToTake='Take with a glass of water.',this.foodInstructions='Take after food.',this.sideEffects='Mild nausea may occur.',this.notes='Continue as advised.',this.initialQuantity=30,this.dailyUsage=1,this.taken=false});Map<String,dynamic>toJson()=>{'id':id,'name':name,'dosage':dosage,'purpose':purpose,'schedule':schedule,'remaining':remaining,'initialQuantity':initialQuantity,'dailyUsage':dailyUsage,'taken':taken};factory Medicine.fromJson(Map<String,dynamic>j)=>Medicine(id:j['id'],name:j['name'],dosage:j['dosage'],purpose:j['purpose'],schedule:j['schedule'],remaining:j['remaining'],initialQuantity:j['initialQuantity']??30,dailyUsage:j['dailyUsage']??1,taken:j['taken']??false);}
class Prescription {final String id, consultationId;final List<Medicine> medicines;const Prescription({required this.id,required this.consultationId,required this.medicines});Map<String,dynamic>toJson()=>{'id':id,'consultationId':consultationId,'medicines':medicines.map((e)=>e.toJson()).toList()};}
class Consultation {final String id,doctorName,summary,hospital,diagnosis,status;final DateTime date;const Consultation({required this.id,required this.doctorName,required this.summary,required this.date,this.hospital='NovaCare Hospital',this.diagnosis='Essential hypertension',this.status='Completed'});Map<String,dynamic>toJson()=>{'id':id,'doctorName':doctorName,'summary':summary,'hospital':hospital,'diagnosis':diagnosis,'status':status,'date':date.toIso8601String()};}
class AppNotification {final String id,title,body,type;final DateTime createdAt;final bool isRead;const AppNotification({required this.id,required this.title,required this.body,required this.type,required this.createdAt,this.isRead=false});Map<String,dynamic>toJson()=>{'id':id,'title':title,'body':body,'type':type,'createdAt':createdAt.toIso8601String(),'isRead':isRead};}
class HealthMetrics {final int heartRate,steps;final double spo2;final Duration sleep;const HealthMetrics({required this.heartRate,required this.steps,required this.spo2,required this.sleep});Map<String,dynamic>toJson()=>{'heartRate':heartRate,'steps':steps,'spo2':spo2,'sleep':sleep.inMinutes};}
class Report {final String id,title,category,url;final DateTime date;const Report({required this.id,required this.title,required this.category,required this.url,required this.date});Map<String,dynamic>toJson()=>{'id':id,'title':title,'category':category,'url':url,'date':date.toIso8601String()};}
typedef UserModel = Patient;
