class Patient { final String id, name, email, medicalId; final DateTime dateOfBirth; const Patient({required this.id,required this.name,required this.email,required this.medicalId,required this.dateOfBirth}); Map<String,dynamic> toJson()=>{'id':id,'name':name,'email':email,'medicalId':medicalId,'dateOfBirth':dateOfBirth.toIso8601String()}; factory Patient.fromJson(Map<String,dynamic> j)=>Patient(id:j['id'],name:j['name'],email:j['email'],medicalId:j['medicalId'],dateOfBirth:DateTime.parse(j['dateOfBirth'])); }
class Doctor { final String id,name,specialty,hospital; const Doctor({required this.id,required this.name,required this.specialty,required this.hospital}); Map<String,dynamic> toJson()=>{'id':id,'name':name,'specialty':specialty,'hospital':hospital}; factory Doctor.fromJson(Map<String,dynamic> j)=>Doctor(id:j['id'],name:j['name'],specialty:j['specialty'],hospital:j['hospital']); }
class Appointment {final String id;final Doctor doctor;final DateTime scheduledAt;final String status;const Appointment({required this.id,required this.doctor,required this.scheduledAt,required this.status});Map<String,dynamic>toJson()=>{'id':id,'doctor':doctor.toJson(),'scheduledAt':scheduledAt.toIso8601String(),'status':status};factory Appointment.fromJson(Map<String,dynamic>j)=>Appointment(id:j['id'],doctor:Doctor.fromJson(j['doctor']),scheduledAt:DateTime.parse(j['scheduledAt']),status:j['status']);}
class Medicine {final String id,name,dosage,purpose,schedule,doctor,howToTake,foodInstructions,sideEffects,notes;final int remaining,initialQuantity,dailyUsage;final bool taken;const Medicine({required this.id,required this.name,required this.dosage,required this.purpose,required this.schedule,required this.remaining,this.doctor='Dr. Ananya Rao',this.howToTake='Take with a glass of water.',this.foodInstructions='Take after food.',this.sideEffects='Mild nausea may occur.',this.notes='Continue as advised.',this.initialQuantity=30,this.dailyUsage=1,this.taken=false});Map<String,dynamic>toJson()=>{'id':id,'name':name,'dosage':dosage,'purpose':purpose,'schedule':schedule,'remaining':remaining,'initialQuantity':initialQuantity,'dailyUsage':dailyUsage,'taken':taken};factory Medicine.fromJson(Map<String,dynamic>j)=>Medicine(id:j['id'],name:j['name'],dosage:j['dosage'],purpose:j['purpose'],schedule:j['schedule'],remaining:j['remaining'],initialQuantity:j['initialQuantity']??30,dailyUsage:j['dailyUsage']??1,taken:j['taken']??false);}
class Prescription {final String id, consultationId;final List<Medicine> medicines;const Prescription({required this.id,required this.consultationId,required this.medicines});Map<String,dynamic>toJson()=>{'id':id,'consultationId':consultationId,'medicines':medicines.map((e)=>e.toJson()).toList()};}
class Consultation {final String id,doctorName,summary,hospital,diagnosis,status;final DateTime date;const Consultation({required this.id,required this.doctorName,required this.summary,required this.date,this.hospital='NovaCare Hospital',this.diagnosis='Essential hypertension',this.status='Completed'});Map<String,dynamic>toJson()=>{'id':id,'doctorName':doctorName,'summary':summary,'hospital':hospital,'diagnosis':diagnosis,'status':status,'date':date.toIso8601String()};}
class AppNotification {final String id,title,body,type;final DateTime createdAt;final bool isRead;const AppNotification({required this.id,required this.title,required this.body,required this.type,required this.createdAt,this.isRead=false});Map<String,dynamic>toJson()=>{'id':id,'title':title,'body':body,'type':type,'createdAt':createdAt.toIso8601String(),'isRead':isRead};}
class HealthMetrics {final int heartRate,steps;final double spo2;final Duration sleep;const HealthMetrics({required this.heartRate,required this.steps,required this.spo2,required this.sleep});Map<String,dynamic>toJson()=>{'heartRate':heartRate,'steps':steps,'spo2':spo2,'sleep':sleep.inMinutes};}
class Report {final String id,title,category,url;final DateTime date;const Report({required this.id,required this.title,required this.category,required this.url,required this.date});Map<String,dynamic>toJson()=>{'id':id,'title':title,'category':category,'url':url,'date':date.toIso8601String()};}
typedef UserModel = Patient;

class Hospital { final String id, name; const Hospital({required this.id, required this.name}); factory Hospital.fromJson(Map<String,dynamic> j)=>Hospital(id:j['id'].toString(),name:(j['name']??'Hospital').toString()); }
class Department { final String id, hospitalId, name; const Department({required this.id,required this.hospitalId,required this.name}); factory Department.fromJson(Map<String,dynamic> j)=>Department(id:j['id'].toString(),hospitalId:(j['hospital_id']??'').toString(),name:(j['name']??'Department').toString()); }
class DoctorDirectoryItem { final String id, firstName, lastName, specialization, qualification, hospital, department; final int experience; final num fee, rating; final bool available; const DoctorDirectoryItem({required this.id,required this.firstName,required this.lastName,required this.specialization,required this.qualification,required this.experience,required this.fee,required this.rating,required this.hospital,required this.department,required this.available}); String get name=>'${firstName.trim()} ${lastName.trim()}'.trim(); factory DoctorDirectoryItem.fromJson(Map<String,dynamic> j){final h=Map<String,dynamic>.from(j['hospital'] as Map? ?? {}),d=Map<String,dynamic>.from(j['department'] as Map? ?? {});return DoctorDirectoryItem(id:j['id'].toString(),firstName:(j['first_name']??'').toString(),lastName:(j['last_name']??'').toString(),specialization:(j['specialization']??'General medicine').toString(),qualification:(j['qualification']??'').toString(),experience:(j['experience_years'] as num? ?? 0).toInt(),fee:j['consultation_fee_inr'] as num? ?? 0,rating:j['rating'] as num? ?? 0,hospital:(h['name']??'Hospital').toString(),department:(d['name']??'Department').toString(),available:j['is_available']==true);}}
class LiveAppointment { final String id, doctorName, hospital, department, status, consultationType, date, time; const LiveAppointment({required this.id,required this.doctorName,required this.hospital,required this.department,required this.status,required this.consultationType,required this.date,required this.time}); factory LiveAppointment.fromJson(Map<String,dynamic> j){final a=Map<String,dynamic>.from(j['appointment'] as Map? ?? j),d=Map<String,dynamic>.from(j['doctor'] as Map? ?? {}),p=Map<String,dynamic>.from(d['profiles'] as Map? ?? {}),h=Map<String,dynamic>.from(d['hospitals'] as Map? ?? {}),dep=Map<String,dynamic>.from(d['departments'] as Map? ?? {});return LiveAppointment(id:a['id'].toString(),doctorName:'${p['first_name']??''} ${p['last_name']??''}'.trim(),hospital:(h['name']??'Hospital').toString(),department:(dep['name']??'Department').toString(),status:(a['status']??'scheduled').toString(),consultationType:(a['consultation_type']??'in_person').toString(),date:(a['appointment_date']??'').toString(),time:(a['appointment_time']??'').toString());}}
