import 'package:flutter/material.dart';
import 'services.dart';
const blue = Color(0xff1769e0);
class LoginPage extends StatefulWidget { const LoginPage({required this.auth, super.key}); final DoctorAuthService auth; @override State<LoginPage> createState() => _LoginState(); }
class _LoginState extends State<LoginPage> { final email = TextEditingController(); final password = TextEditingController(); bool loading = false; String? error;
  Future<void> login() async { setState(() => loading = true); try { await widget.auth.signIn(email.text.trim(), password.text); if (mounted) setState(() {}); } catch (_) { setState(() => error = 'Unable to sign in. Check your doctor account and try again.'); } finally { if (mounted) setState(() => loading = false); } }
  @override Widget build(BuildContext context) => Scaffold(body: Center(child: SingleChildScrollView(padding: const EdgeInsets.all(24), child: Column(children: [const Icon(Icons.medical_services, size: 64, color: blue), const SizedBox(height: 16), const Text('Doctor workspace', style: TextStyle(fontSize: 28, fontWeight: FontWeight.w800)), TextField(controller: email, decoration: const InputDecoration(labelText: 'Email')), TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: 'Password')), if (error != null) Text(error!, style: const TextStyle(color: Colors.red)), const SizedBox(height: 20), FilledButton(onPressed: loading ? null : login, child: Text(loading ? 'Signing in…' : 'Sign in'))]))));
}
class DoctorHome extends StatefulWidget { const DoctorHome({required this.auth, super.key}); final DoctorAuthService auth; @override State<DoctorHome> createState() => _DoctorHomeState(); }
class _DoctorHomeState extends State<DoctorHome> { late final DoctorRepository repo = DoctorRepository(DoctorApiClient(widget.auth)); late Future<Map<String, dynamic>> profile; late Future<List<Map<String, dynamic>>> appointments; @override void initState() { super.initState(); refresh(); } void refresh() { profile = repo.doctor(); appointments = repo.appointments(); } String name(Map<String, dynamic> p) => '${p['first_name'] ?? ''} ${p['last_name'] ?? ''}'.trim(); @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Doctor dashboard'), actions: [IconButton(onPressed: () async { await widget.auth.signOut(); if (mounted) setState(() {}); }, icon: const Icon(Icons.logout))]), body: RefreshIndicator(onRefresh: () async { setState(refresh); }, child: ListView(padding: const EdgeInsets.all(20), children: [FutureBuilder<Map<String, dynamic>>(future: profile, builder: (context, s) { if (s.connectionState == ConnectionState.waiting) return const LinearProgressIndicator(); if (s.hasError) return const Text('Unable to load doctor profile.'); final p = s.data!; return Card(child: ListTile(title: Text(name(p)), subtitle: Text('${p['specialization'] ?? 'Doctor'} • ${p['qualification'] ?? ''}'))); }), const SizedBox(height: 16), const Text("Today's appointments", style: TextStyle(fontSize: 20, fontWeight: FontWeight.w800)), FutureBuilder<List<Map<String, dynamic>>>(future: appointments, builder: (context, s) { if (s.connectionState == ConnectionState.waiting) return const CircularProgressIndicator(); if (s.hasError) return const Text('Unable to load appointments.'); final items = s.data ?? []; if (items.isEmpty) return const Text('No appointments assigned to you.'); return Column(children: items.map((item) => AppointmentCard(item: item, repo: repo, onSaved: () => setState(refresh))).toList()); })]))); }
class AppointmentCard extends StatelessWidget { const AppointmentCard({required this.item, required this.repo, required this.onSaved, super.key}); final Map<String, dynamic> item; final DoctorRepository repo; final VoidCallback onSaved; @override Widget build(BuildContext context) { final a = Map<String, dynamic>.from(item['appointment'] as Map? ?? item); final p = Map<String, dynamic>.from(item['patient'] as Map? ?? {}); return Card(child: ListTile(title: Text('${p['first_name'] ?? ''} ${p['last_name'] ?? ''}'), subtitle: Text('${a['appointment_date'] ?? ''} ${a['appointment_time'] ?? ''}\n${a['status'] ?? ''}'), onTap: () => showDialog(context: context, builder: (_) => ConsultationDialog(appointmentId: a['id'].toString(), repo: repo, onSaved: onSaved)))); } }
class ConsultationDialog extends StatefulWidget { const ConsultationDialog({required this.appointmentId, required this.repo, required this.onSaved, super.key}); final String appointmentId; final DoctorRepository repo; final VoidCallback onSaved; @override State<ConsultationDialog> createState() => _ConsultationDialogState(); }
class _ConsultationDialogState extends State<ConsultationDialog> { final symptoms = TextEditingController(); final diagnosis = TextEditingController(); final plan = TextEditingController(); bool saving = false; String? error; Future<void> save() async { setState(() => saving = true); try { await widget.repo.consultation({'appointment_id': widget.appointmentId, 'symptoms': symptoms.text, 'diagnosis': diagnosis.text, 'treatment_plan': plan.text, 'consultation_type': 'in_person'}); if (mounted) { Navigator.pop(context); widget.onSaved(); } } catch (_) { setState(() => error = 'Unable to save consultation. Please try again.'); } finally { if (mounted) setState(() => saving = false); } } @override Widget build(BuildContext context) => AlertDialog(title: const Text('Consultation'), content: SingleChildScrollView(child: Column(children: [TextField(controller: symptoms, decoration: const InputDecoration(labelText: 'Symptoms')), TextField(controller: diagnosis, decoration: const InputDecoration(labelText: 'Diagnosis')), TextField(controller: plan, decoration: const InputDecoration(labelText: 'Treatment plan')), if (error != null) Text(error!, style: const TextStyle(color: Colors.red))])), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: saving ? null : save, child: Text(saving ? 'Saving…' : 'Save'))]); }
