create extension if not exists "uuid-ossp";
create extension if not exists vector;
create type public.user_role as enum ('patient','doctor','staff','hospital_admin','super_admin');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, role public.user_role not null default 'patient', full_name text not null, hospital_id uuid, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.hospitals (id uuid primary key default uuid_generate_v4(), name text not null, city text not null, created_at timestamptz not null default now());
alter table public.profiles add constraint profiles_hospital_fk foreign key (hospital_id) references public.hospitals(id);
create table public.departments (id uuid primary key default uuid_generate_v4(), hospital_id uuid not null references public.hospitals(id) on delete cascade, name text not null, unique(hospital_id,name));
create table public.patients (id uuid primary key references public.profiles(id) on delete cascade, medical_id text not null unique, date_of_birth date, blood_group text, assigned_doctor_id uuid, created_at timestamptz not null default now());
create table public.doctors (id uuid primary key references public.profiles(id) on delete cascade, department_id uuid references public.departments(id), license_number text not null unique, specialization text, consultation_fee numeric(10,2));
alter table public.patients add constraint patients_doctor_fk foreign key (assigned_doctor_id) references public.doctors(id);
create table public.appointments (id uuid primary key default uuid_generate_v4(), patient_id uuid not null references public.patients(id), doctor_id uuid not null references public.doctors(id), scheduled_at timestamptz not null, status text not null check (status in ('scheduled','waiting','in_progress','completed','cancelled')), reason text, created_at timestamptz not null default now());
create table public.consultations (id uuid primary key default uuid_generate_v4(), appointment_id uuid references public.appointments(id), patient_id uuid not null references public.patients(id), doctor_id uuid not null references public.doctors(id), summary text, diagnosis text, confidence numeric(4,3), approved_at timestamptz, created_at timestamptz not null default now());
create table public.medical_documents (id uuid primary key default uuid_generate_v4(), patient_id uuid not null references public.patients(id), consultation_id uuid references public.consultations(id), bucket_path text not null, document_type text not null, created_at timestamptz not null default now());
create table public.patient_embeddings (id uuid primary key default uuid_generate_v4(), patient_id uuid not null references public.patients(id), source_document_id uuid references public.medical_documents(id), content text not null, embedding vector(1536), created_at timestamptz not null default now());
create index appointments_doctor_time_idx on public.appointments(doctor_id, scheduled_at desc);
create index consultations_patient_time_idx on public.consultations(patient_id, created_at desc);
create index patient_embeddings_vector_idx on public.patient_embeddings using ivfflat (embedding vector_cosine_ops) with (lists=100);
alter table public.profiles enable row level security; alter table public.patients enable row level security; alter table public.doctors enable row level security; alter table public.appointments enable row level security; alter table public.consultations enable row level security; alter table public.medical_documents enable row level security; alter table public.patient_embeddings enable row level security;
create policy "profile_self_read" on public.profiles for select to authenticated using (id = (select auth.uid()));
create policy "patient_self_read" on public.patients for select to authenticated using (id = (select auth.uid()));
create policy "patient_documents_self_read" on public.medical_documents for select to authenticated using (patient_id = (select auth.uid()));
insert into storage.buckets (id,name,public) values ('medical-documents','medical-documents',false) on conflict do nothing;
