import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../theme/app_theme.dart';
import '../widgets/ui.dart';

class HomeScreen extends StatelessWidget { const HomeScreen({super.key});
 @override Widget build(BuildContext context)=>RefreshIndicator(onRefresh:()=>Future.delayed(const Duration(milliseconds:700)),child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.only(bottom:28),children:[
  Padding(padding:const EdgeInsets.fromLTRB(20,18,20,12),child:Row(children:[const AppLogo(),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Good Morning, Ashish',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800)),Text(_todayLabel(),style:const TextStyle(color:AppTheme.muted,fontSize:12))])),const Icon(Icons.notifications_none_rounded),const SizedBox(width:14),const CircleAvatar(radius:19,backgroundColor:Color(0xFFDCE7FF),child:Text('A',style:TextStyle(color:AppTheme.blue,fontWeight:FontWeight.w800)))])),
  Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:SoftCard(color:const Color(0xFFEAF2FF),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.auto_awesome_rounded,color:AppTheme.blue),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Your AI health summary',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:6),const Text('One appointment today. Your sleep improved by 14%, and one medicine is pending.',style:TextStyle(color:AppTheme.muted,height:1.45,fontSize:13))]))]))),
  Padding(padding:const EdgeInsets.fromLTRB(20,22,20,0),child:InkWell(onTap:()=>context.go('/record'),borderRadius:BorderRadius.circular(26),child:Container(height:226,padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[AppTheme.blue,Color(0xFF477BF0),AppTheme.cyan]),borderRadius:BorderRadius.circular(26),boxShadow:const [BoxShadow(color:Color(0x402459E0),blurRadius:24,offset:Offset(0,10))]),child:Stack(children:[Positioned(right:-16,bottom:-25,child:Icon(Icons.graphic_eq_rounded,size:165,color:Colors.white.withValues(alpha:.15))),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const StatusPill('AI CLINICAL ASSISTANT',Colors.white),const Spacer(),const Text('Start new voice\nconsultation',style:TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.w800,height:1.15)),const SizedBox(height:8),const Text('Secure clinical recording • review required',style:TextStyle(color:Colors.white70,fontSize:12)),const SizedBox(height:12),Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16)),child:const Icon(Icons.mic_rounded,color:AppTheme.blue)),const SizedBox(width:12),const Text('Record securely',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w700))])])])))),
  const SectionTitle('Today at a glance'), Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:SoftCard(child:Row(children:[Container(width:46,height:46,decoration:BoxDecoration(color:const Color(0xFFEAF9F5),borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.calendar_month_rounded,color:AppTheme.emerald)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Dr. Meera Kapoor',style:Theme.of(context).textTheme.titleSmall?.copyWith(fontWeight:FontWeight.w800)),const Text('Cardiology • NovaCare Hospital',style:TextStyle(fontSize:12,color:AppTheme.muted))])),const Column(crossAxisAlignment:CrossAxisAlignment.end,children:[Text('10:30 AM',style:TextStyle(fontWeight:FontWeight.w800,color:AppTheme.blue)),const Text('Join',style:TextStyle(fontSize:12,color:AppTheme.blue))])]))),
  const SectionTitle("Today's medicines",action:'View all'), Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:SoftCard(child:Column(children:[_medicine('Metformin','500 mg • after breakfast',true),const Divider(height:25),_medicine('Atorvastatin','10 mg • 9:00 PM',false)]))),
  const SectionTitle('Health snapshot'), Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:GridView.count(crossAxisCount:2,childAspectRatio:1.5,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:12,mainAxisSpacing:12,children:const [_Vital('Heart rate','72 bpm',Icons.favorite_rounded,Color(0xFFFFE9ED)),_Vital('Sleep','7h 42m',Icons.dark_mode_rounded,Color(0xFFE9EDFF)),_Vital('SpO₂','98%',Icons.air_rounded,Color(0xFFE8F9FC)),_Vital('Steps','6,248',Icons.directions_walk_rounded,Color(0xFFEAF9F5))])),
  const SectionTitle('Recent activity'),Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:SoftCard(child:Column(children:[_activity(Icons.description_rounded,'Prescription updated','Dr. Ananya Rao • 2h ago'),const Divider(),_activity(Icons.check_circle_rounded,'Medicine reminder completed','Metformin • 8:10 AM'),const Divider(),_activity(Icons.biotech_rounded,'Lab report added','Vitamin D panel • Yesterday')]))),
 ]));
 Widget _medicine(String a,String b,bool done)=>Row(children:[CircleAvatar(backgroundColor:done?const Color(0xFFEAF9F5):const Color(0xFFFFF3DF),child:Icon(done?Icons.check_rounded:Icons.schedule_rounded,color:done?AppTheme.emerald:const Color(0xFFE79A22))),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontWeight:FontWeight.w800)),Text(b,style:const TextStyle(fontSize:12,color:AppTheme.muted))])),StatusPill(done?'Taken':'Pending',done?AppTheme.emerald:const Color(0xFFE79A22))]);
 Widget _activity(IconData i,String a,String b)=>Row(children:[CircleAvatar(radius:18,backgroundColor:const Color(0xFFF0F4FC),child:Icon(i,size:18,color:AppTheme.blue)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:13)),Text(b,style:const TextStyle(fontSize:11,color:AppTheme.muted))])),const Icon(Icons.chevron_right_rounded,color:AppTheme.muted)]);
 String _todayLabel(){final d=DateTime.now();const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];const months=['January','February','March','April','May','June','July','August','September','October','November','December'];return '${days[d.weekday-1]}, ${d.day} ${months[d.month-1]} ${d.year}';}
}
class _Vital extends StatelessWidget {final String a,b;final IconData i;final Color c;const _Vital(this.a,this.b,this.i,this.c);@override Widget build(BuildContext context)=>SoftCard(padding:const EdgeInsets.all(14),child:Row(children:[Container(padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:c,borderRadius:BorderRadius.circular(11)),child:Icon(i,color:AppTheme.blue,size:18)),const SizedBox(width:9),Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text(b,style:const TextStyle(fontWeight:FontWeight.w800)),Text(a,style:const TextStyle(fontSize:10,color:AppTheme.muted))]) ]));}
