import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/app_providers.dart';

class LiveConsultationsScreen extends ConsumerWidget { const LiveConsultationsScreen({super.key}); @override Widget build(BuildContext context,WidgetRef ref)=>_LiveList(title:'Consultations',provider:patientConsultationsProvider,empty:'No consultations yet.',builder:(row)=>ExpansionTile(title:Text((row['diagnosis']??'Consultation').toString()),subtitle:Text('${row['consultation_date']??row['created_at']??''} • ${row['doctor']?['first_name']??''} ${row['doctor']?['last_name']??''}'),children:[ListTile(title:Text('Symptoms: ${(row['symptoms']??'Not recorded')}')),ListTile(title:Text('Treatment: ${(row['treatment_plan']??'Not recorded')}')),ListTile(title:Text('Follow-up: ${(row['follow_up_date']??'Not recorded')}'))])); }
class LivePrescriptionsScreen extends ConsumerWidget { const LivePrescriptionsScreen({super.key}); @override Widget build(BuildContext context,WidgetRef ref)=>_LiveList(title:'Prescriptions',provider:patientPrescriptionsProvider,empty:'No prescriptions yet.',builder:(row)=>ExpansionTile(title:Text('Prescription • ${row['prescription_date']??''}'),subtitle:Text((row['notes']??'').toString()),children:[...(row['items'] as List? ?? const []).map((item)=>ListTile(title:Text((item['medicine']?['name']??'Medicine').toString()),subtitle:Text('Dosage: ${item['dosage']??''} • Frequency: ${item['frequency']??''} • Duration: ${item['duration']??''}\nInstructions: ${item['instructions']??''}')))])); }
class LiveReportsScreen extends ConsumerWidget { const LiveReportsScreen({super.key}); @override Widget build(BuildContext context,WidgetRef ref)=>_LiveList(title:'Reports',provider:patientReportsProvider,empty:'No reports available.',builder:(row)=>ListTile(title:Text((row['report_type']??'Report').toString()),subtitle:Text('${row['report_date']??''}\n${row['findings']??'No findings recorded.'}\n${row['recommendations']??''}'))); }
class LiveInsuranceScreen extends ConsumerWidget { const LiveInsuranceScreen({super.key}); @override Widget build(BuildContext context,WidgetRef ref){final state=ref.watch(patientInsuranceProvider);return Scaffold(appBar:AppBar(title:const Text('Insurance')),body:state.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(_,__)=>Center(child:TextButton(onPressed:()=>ref.invalidate(patientInsuranceProvider),child:const Text('Unable to load insurance. Retry'))),data:(data)=>ListView(padding:const EdgeInsets.all(16),children:[_LiveList(title:'Policies',provider:FutureProvider<List<Map<String,dynamic>>>((_) async => List<Map<String,dynamic>>.from(data['policies']??const [])),empty:'No policies available.',builder:(row)=>ListTile(title:Text('${row['provider_name']??row['policy_type']??'Policy'}'),subtitle:Text('${row['policy_number']??''}\nCoverage: ${row['sum_insured']??''} • Premium: ${row['premium_amount']??''}\n${row['start_date']??''} – ${row['end_date']??''}')))]) );}}
class _LiveList extends ConsumerWidget { const _LiveList({required this.title,required this.provider,required this.empty,required this.builder}); final String title,empty; final FutureProvider<List<Map<String,dynamic>>> provider; final Widget Function(Map<String,dynamic>) builder; @override Widget build(BuildContext context,WidgetRef ref){final state=ref.watch(provider);return Scaffold(appBar:AppBar(title:Text(title)),body:state.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Unable to load live clinical data.'),TextButton(onPressed:()=>ref.invalidate(provider),child:const Text('Retry'))])),data:(items)=>items.isEmpty?Center(child:Text(empty)):RefreshIndicator(onRefresh:()=>ref.refresh(provider.future),child:ListView(padding:const EdgeInsets.all(12),children:items.map((row)=>Card(child:builder(row))).toList()))));}}
